// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB5PykncYDzQmw_nLfeVWoiDU4UxtDGi4',
    appId: '1:909788251285:web:cee9e91c13c1985406079c',
    messagingSenderId: '909788251285',
    projectId: 'cuaca-bcb7e',
    authDomain: 'cuaca-bcb7e.firebaseapp.com',
    storageBucket: 'cuaca-bcb7e.appspot.com',
    measurementId: 'G-BXJYBRJ78F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAltI7azsZplKvzRGS7O23UlxHQdxa0DTM',
    appId: '1:909788251285:android:0964e4337bac237706079c',
    messagingSenderId: '909788251285',
    projectId: 'cuaca-bcb7e',
    storageBucket: 'cuaca-bcb7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi2QTSLqeNcY8fy2TjeJ5PAtt7ut12W9c',
    appId: '1:909788251285:ios:ac08e7c43333cb6906079c',
    messagingSenderId: '909788251285',
    projectId: 'cuaca-bcb7e',
    storageBucket: 'cuaca-bcb7e.appspot.com',
    iosClientId: '909788251285-3v1o9ttn13o7llu4aa6d9djeu433563i.apps.googleusercontent.com',
    iosBundleId: 'com.example.modul3',
  );
}
